# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    AiselPageBundle:
                        type: annotation
                    AiselAddressingBundle:
                        type: annotation
                    AiselFrontendUserBundle:
                        type: annotation
                    AiselBackendUserBundle:
                        type: annotation
                    AiselConfigBundle:
                        type: annotation
                    AiselCartBundle:
                        type: annotation
                    AiselProductBundle:
                        type: annotation
                    AiselNavigationBundle:
                        type: annotation
                    AiselOrderBundle:
                        type: annotation

                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
#                    payum:
#                        is_bundle: false
#                        type: xml
#                        dir: %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping
#                        prefix: Payum\Core\Model

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true