<?php

namespace Aisel\AddressingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends AbstractCollectionRepository
{
    protected $entity = 'AiselAddressingBundle:Region';

}
