<?php

namespace Aisel\AddressingBundle\Entity;

use Aisel\ResourceBundle\Repository\CollectionRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends CollectionRepository
{
    protected $model = 'AiselAddressingBundle:City';

}
