<?php

namespace Aisel\AddressingBundle\Entity;

use Aisel\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends AbstractCollectionRepository
{
    protected $entity = 'AiselAddressingBundle:City';

}
