<?php

namespace Aisel\AddressingBundle\Entity;

use Aisel\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends AbstractCollectionRepository
{
    protected $entity = 'AiselAddressingBundle:Country';

}
