<?php

namespace Aisel\AddressingBundle\Entity;

use Aisel\ResourceBundle\Repository\CollectionRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends CollectionRepository
{
    protected $model = 'AiselAddressingBundle:Country';

}
