<?php

namespace Aisel\AddressingBundle\Entity;

use Aisel\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends AbstractCollectionRepository
{
    protected $entity = 'AiselAddressingBundle:Region';

}
