<?php

namespace Aisel\AddressingBundle\Entity;

use Aisel\ResourceBundle\Repository\CollectionRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends CollectionRepository
{
    protected $model = 'AiselAddressingBundle:Region';

}
