<?php

namespace Aisel\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    private $query = '';
    private $pageCurrent = 1;
    private $pageLimit = 1;
    private $pageSkip = 1;
    private $pageOrder = 'id';
    private $pageOrderBy = 'ASC';

    private function mapRequest($params) {

        if ( isset($params['current'])) {
            $this->pageCurrent = $params['current'];
        } else {
            $this->pageCurrent = 1;
        }
        if ( isset($params['limit'])) {
            $this->pageLimit = $params['limit'];
        } else {
            $this->pageLimit = 5;
        }

        // ordering
        if ( isset($params['order'])) {
            $this->pageOrder = $params['order'];
        } else {
            $this->pageOrder = 'id';
        }
        if ( isset($params['orderby'])) {
            $this->pageOrderBy = $params['orderby'];
        } else {
            $this->pageOrderBy = 'ASC';
        }

        // search
        if ( isset($params['query'])) {
            $this->query = $params['query'];
        }
        $this->pageSkip = ($this->pageCurrent-1) * $this->pageLimit;
    }


    /*
     * Get page total
     *
     * @return int value
     * */

    public function getTotalFromRequest($params)
    {
        $this->mapRequest($params);

        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('COUNT(p.id)')
            ->from('AiselPageBundle:Page', 'p')
            ->where('p.pageStatus = :page_status');

        if ($this->query != '') {
            $qb->andWhere('p.content LIKE :search')->setParameter('search', '%'.$this->query.'%');
        }
        $r = $qb->setParameter('page_status', 1)
                ->getQuery()->getSingleScalarResult();

        if (!$r) return 0;
        return $r;
    }

    /*
     * Get pages based on limit, current pagination and search query
     *
     * @return pages
     * */

    public function getCurrentPagesFromRequest($params)
    {
        $this->mapRequest($params);

        $qb = $this->getEntityManager()->createQueryBuilder();
        $r = $qb->select('p.id, p.title, p.content, p.dateCreated')
            ->from('AiselPageBundle:Page', 'p')
            ->setMaxResults($this->pageLimit)
            ->setFirstResult($this->pageSkip)
            ->getQuery()
            ->execute();

        return $r;
    }

    /*
     * Get pages based on limit, current pagination and search query
     *
     * @return pages
     * */

    public function searchFromRequest($params)
    {
        $this->mapRequest($params);

        $qb = $this->getEntityManager()->createQueryBuilder();
        $r = $qb->select('p.id, p.title, p.content, p.dateCreated')
            ->from('AiselPageBundle:Page', 'p')
            ->where('p.content LIKE :search')->setParameter('search', '%'.$this->query.'%')
            ->setMaxResults($this->pageLimit)
            ->setFirstResult($this->pageSkip)
            ->orderBy('p.'.$this->pageOrder, $this->pageOrderBy)
            ->getQuery()
            ->execute();

        return $r;
    }

}
