<?php

/*
 * This file is part of the Aisel package.
 *
 * (c) Ivan Proskuryakov
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Aisel\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{

    /*
     * Find categories by url
     *
     * @return int value
     * */

    public function findTotalByURL($url, $categoryId = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('COUNT(c.id)')
            ->from('AiselCategoryBundle:Category', 'c')
            ->where('c.metaUrl = :url')->setParameter('url', $url);

        if ($categoryId) {
            $qb->andWhere('c.id != :categoryId')->setParameter('categoryId',$categoryId);
        }
        $found = $qb->getQuery()->getSingleScalarResult();

        return $found;
    }

}
