<?php

namespace Aisel\UserBundle\Entity;

//use Proxies\__CG__\Application\Sonata\UserBundle\Entity\User;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * FrontUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontendUserRepository extends EntityRepository
{



}
