<?php

namespace Aisel\ProductBundle\Entity;

use Aisel\ResourceBundle\Repository\CollectionRepository;

/**
 * CategoryRepository for Products
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends CollectionRepository
{

    protected $model = 'AiselProductBundle:Category';

}
