<?php

/*
 * This file is part of the Aisel package.
 *
 * (c) Ivan Proskuryakov
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Aisel\ProductBundle\Entity;

use Aisel\ResourceBundle\Repository\CollectionRepository;

/**
 * CategoryRepository for Products
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends CollectionRepository
{

    protected $model = 'AiselProductBundle:Category';

}
