<?php

namespace Aisel\ProductBundle\Entity;

use Aisel\ResourceBundle\Entity\CategoryRepository as BaseCategoryRepository;

/**
 * CategoryRepository for Products
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseCategoryRepository
{
    protected $categoryEntity = 'AiselProductBundle:Category';
}
